---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cfgedit
  name: cfgedit
  namespace: default

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: cfgedit
  name: cfgedit
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "update","patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cfgedit
  labels:
    app: cfgedit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cfgedit
subjects:
  - kind: ServiceAccount
    name: cfgedit
    namespace: default

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: cfgedit
  name: cfgedit
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cfgedit
  template:
    metadata:
      labels:
        app: cfgedit
    spec:
      containers:
        - name: cfgedit
          image: swr.cn-north-1.myhuaweicloud.com/donghalcyon/editcfg:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          command: ["/cfgedit"]
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
      serviceAccountName: cfgedit
      # nodeSelector:
      #   "kubernetes.io/os": linux
      # tolerations:
      #   - key: "CriticalAddonsOnly"
      #     operator: "Exists"
      #   - key: node-role.kubernetes.io/master
      #     effect: NoSchedule

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: cfgedit
  name: cfgedit
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: cfgedit

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
  annotations:
    cfgedit/enable: 'true'
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true




